### PR TITLE
INSPECTIT-2195: Option to write long term data to influxDB

### PR DESCRIPTION
**Pull request by AlexanderWert**
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit/156)

### CODE REVIEW

**Comment by pbouillet** [comment]
Tests are completely missing. I understand that this implementation will be replaced at some time, but until then, this will be included and useable by anyone. Let's at least have some tests to ensure that everything works correctly.

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[inspectit.server/src/main/external-resources/config/default.xml, line 318 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/156#-KQeiNd-MllloFuw-8JI:-KQeiNd-MllloFuw-8JJ:br9zkl2) ([raw file](https://github.com/inspectit/inspectit/blob/cef8d1b46e045a6db8d07185ff3d6e64b5882525/inspectit.server/src/main/external-resources/config/default.xml#L318)):*
> ```XML
> 		</properties>
> 	</section>
> 	<section name="Time Series Data">
> ```

It's not clear from the properties that only influx database is currently supported. We should clearly state this.
Furthermore, this section and the database definition should be put in a common section (but I don't know currently if it is possible to have a section without any properties)

---

*[inspectit.server/src/main/external-resources/config/default.xml, line 320 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/156#-KQegvZ65U4kBQ9CbQr9:-KQegvZ65U4kBQ9CbQrA:bxqan1o) ([raw file](https://github.com/inspectit/inspectit/blob/cef8d1b46e045a6db8d07185ff3d6e64b5882525/inspectit.server/src/main/external-resources/config/default.xml#L320)):*
> ```XML
> 	<section name="Time Series Data">
> 		<properties>
> 			<boolean-property name="Write Data to local DB" default-value="true" server-restart-required="false" logical-name="timeseries.dataPersistence.active" advanced="false" description="If activated, all time series data (business transaction timings, resource utilizations, etc.) will be (also) written to the local inspectIT server database."></boolean-property>
> ```

Why allow both. The thing here is that writing the measurements into the local database will become a problem very soon if used in production. To prevent this, I would make an either or for local / influx db (and in the future even provide more connection possibilities). Your opinion on this?

---

*[inspectit.server/src/main/external-resources/config/default.xml, line 331 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/156#-KQeihfurK9vuVOuFAtl:-KQeihfvpEBG4jHEVfvz:b-adpglu) ([raw file](https://github.com/inspectit/inspectit/blob/cef8d1b46e045a6db8d07185ff3d6e64b5882525/inspectit.server/src/main/external-resources/config/default.xml#L331)):*
> ```XML
> 			<string-property name="Password" default-value="password" server-restart-required="false" logical-name="influxdb.passwd" advanced="false" description="The password to be used to connect to the influxDB instance."></string-property>
> 			<string-property name="Database" default-value="inspectit" server-restart-required="false" logical-name="influxdb.database" advanced="false" description="The database name in the influxDB instance to write the data to."></string-property>
> 			<string-property name="RetentionPolicy" default-value="autogen" server-restart-required="false" logical-name="influxdb.retentionPolicy" advanced="true" description="Retention policy for the influxDB database."></string-property>
> ```

Something that is currently missing but which I would really like to have here (and for the database section, too) is a "Test" Button to identify if the configuration really works out.

---

*[inspectit.server/src/main/java/rocks/inspectit/server/processor/impl/PersistingCmrProcessor.java, line 27 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/156#-KQenED-xwxapJK6z4Zn:-KQenED-xwxapJK6z4Zo:btrmoql) ([raw file](https://github.com/inspectit/inspectit/blob/cef8d1b46e045a6db8d07185ff3d6e64b5882525/inspectit.server/src/main/java/rocks/inspectit/server/processor/impl/PersistingCmrProcessor.java#L27)):*
> ```Java
> 
> 	/**
> 	 * List of classes that can be saved by this simple saver.
> ```

javadoc is the same for both fields

---

*[inspectit.server/src/main/java/rocks/inspectit/server/processor/impl/PersistingCmrProcessor.java, line 35 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/156#-KQejValG6HvHPygzf-b:-KQejValG6HvHPygzf-c:bki3qnk) ([raw file](https://github.com/inspectit/inspectit/blob/cef8d1b46e045a6db8d07185ff3d6e64b5882525/inspectit.server/src/main/java/rocks/inspectit/server/processor/impl/PersistingCmrProcessor.java#L35)):*
> ```Java
> 	 */
> 	@Value("${timeseries.dataPersistence.active}")
> 	boolean persistOptionalData;
> ```

The mandatory / optional stuff confuses me in here. Even though you deactivate the saving into the sql database you will still write some data? I wouldn't do this for now as this makes everything more complicated

---

*[inspectit.server/src/main/java/rocks/inspectit/server/processor/impl/TimerDataChartingCmrProcessor.java, line 91 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/156#-KQenN5EbJrEx9aJm88l:-KQenN5EbJrEx9aJm88m:b-rkzsx1) ([raw file](https://github.com/inspectit/inspectit/blob/cef8d1b46e045a6db8d07185ff3d6e64b5882525/inspectit.server/src/main/java/rocks/inspectit/server/processor/impl/TimerDataChartingCmrProcessor.java#L91)):*
> ```Java
> 	@Override
> 	public boolean canBeProcessed(DefaultData defaultData) {
> 		return persistTimeSeriesData && (defaultData instanceof TimerData) && ((TimerData) defaultData).isCharting();
> ```

wouldn't it be possible to completely remove this processor from the chain instead of always returning e.g. false? don't know if this would be easy to add

---

*[inspectit.server/src/main/java/rocks/inspectit/server/processor/tsdb/impl/BusinessTransactionToTsdbCmrProcessor.java, line 29 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/156#-KQenl_Davm3NpAk1x0k:-KQenl_EUP0McpWu6uIl:b-lpaxdr) ([raw file](https://github.com/inspectit/inspectit/blob/cef8d1b46e045a6db8d07185ff3d6e64b5882525/inspectit.server/src/main/java/rocks/inspectit/server/processor/tsdb/impl/BusinessTransactionToTsdbCmrProcessor.java#L29)):*
> ```Java
>  *
>  */
> public class BusinessTransactionToTsdbCmrProcessor extends AbstractCmrDataProcessor {
> ```

let's name the class with influx to make it concrete for now. In the future, I can think of having an intermediate layer in which you can define where the time series will be stored to. But for now, influx is the way to go and directly accessed.

---

*[inspectit.server/src/main/java/rocks/inspectit/server/processor/tsdb/impl/BusinessTransactionToTsdbCmrProcessor.java, line 71 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/156#-KQep-chqKU1TjsoCM00:-KQep-chqKU1TjsoCM01:bki3rto) ([raw file](https://github.com/inspectit/inspectit/blob/cef8d1b46e045a6db8d07185ff3d6e64b5882525/inspectit.server/src/main/java/rocks/inspectit/server/processor/tsdb/impl/BusinessTransactionToTsdbCmrProcessor.java#L71)):*
> ```Java
> 	 */
> 	@Autowired
> 	ICachedDataService cachedDataService;
> ```

These 2 services aren't meant to be called from inside the application but only from the UI / agent as they guarantee some transaction behavior or do have some interceptors in place etc. If some logic is needed which is in these services, we should extract them into own classes. Otherwise the layers we have will get messed up.

---

*[inspectit.server/src/main/java/rocks/inspectit/server/processor/tsdb/impl/BusinessTransactionToTsdbCmrProcessor.java, line 97 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/156#-KQepVHFLhmV-5DzEBIT:-KQepVHFLhmV-5DzEBIU:b3poreu) ([raw file](https://github.com/inspectit/inspectit/blob/cef8d1b46e045a6db8d07185ff3d6e64b5882525/inspectit.server/src/main/java/rocks/inspectit/server/processor/tsdb/impl/BusinessTransactionToTsdbCmrProcessor.java#L97)):*
> ```Java
> 			PlatformIdent pIdent = globalDataAccessService.getCompleteAgent(defaultData.getPlatformIdent());
> 			agentName = pIdent.getAgentName();
> 		} catch (BusinessException e) {
> ```

if we do get an exception anywhere, we should at least log it.

---

*[inspectit.server/src/main/java/rocks/inspectit/server/processor/tsdb/impl/ClassloadingToTsdbCmrProcessor.java, line 61 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/156#-KQeq47R2fGUqWFY5Ib9:-KQeq47S4VBPV-VHis3z:b20jyt9) ([raw file](https://github.com/inspectit/inspectit/blob/cef8d1b46e045a6db8d07185ff3d6e64b5882525/inspectit.server/src/main/java/rocks/inspectit/server/processor/tsdb/impl/ClassloadingToTsdbCmrProcessor.java#L61)):*
> ```Java
> 	 */
> 	@Autowired
> 	IInfluxDBService influxDbService;
> ```

Same comment for these 2 services as above, if it occurs again, I'll skip the comment :smile: 

---

*[inspectit.server/src/main/java/rocks/inspectit/server/processor/tsdb/impl/ClassloadingToTsdbCmrProcessor.java, line 80 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/156#-KQeqBBBIfDJO1fbTiUD:-KQeqBBC_DG4y2l35bJc:b-71rwc1) ([raw file](https://github.com/inspectit/inspectit/blob/cef8d1b46e045a6db8d07185ff3d6e64b5882525/inspectit.server/src/main/java/rocks/inspectit/server/processor/tsdb/impl/ClassloadingToTsdbCmrProcessor.java#L80)):*
> ```Java
> 			agentName = pIdent.getAgentName();
> 		} catch (BusinessException e) {
> 			agentName = TsdbPersistingCmrProcessor.VALUE_NOT_AVAILABLE;
> ```

same comment here with the exception as above

---

*[inspectit.server/src/main/java/rocks/inspectit/server/processor/tsdb/impl/SystemDataToTsdbCmrProcessor.java, line 21 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/156#-KQeqwGMh_rm02Xbwdft:-KQeqwGMh_rm02Xbwdfu:b5fubzl) ([raw file](https://github.com/inspectit/inspectit/blob/cef8d1b46e045a6db8d07185ff3d6e64b5882525/inspectit.server/src/main/java/rocks/inspectit/server/processor/tsdb/impl/SystemDataToTsdbCmrProcessor.java#L21)):*
> ```Java
> 
> /***
> ```

javadoc

---

*[inspectit.server/src/main/java/rocks/inspectit/server/processor/tsdb/impl/SystemDataToTsdbCmrProcessor.java, line 53 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/156#-KQer-GzY23El-iuzEt1:-KQer-GzY23El-iuzEt2:bb6td3r) ([raw file](https://github.com/inspectit/inspectit/blob/cef8d1b46e045a6db8d07185ff3d6e64b5882525/inspectit.server/src/main/java/rocks/inspectit/server/processor/tsdb/impl/SystemDataToTsdbCmrProcessor.java#L53)):*
> ```Java
> 
> 	/**
> 	 * Bott class path field.
> ```

Boot

---

*[inspectit.server/src/main/java/rocks/inspectit/server/processor/tsdb/impl/SystemDataToTsdbCmrProcessor.java, line 55 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/156#-KQer4s1M2lDHekmlFWM:-KQer4s1M2lDHekmlFWN:b-7zesuv) ([raw file](https://github.com/inspectit/inspectit/blob/cef8d1b46e045a6db8d07185ff3d6e64b5882525/inspectit.server/src/main/java/rocks/inspectit/server/processor/tsdb/impl/SystemDataToTsdbCmrProcessor.java#L55)):*
> ```Java
> 	 * Bott class path field.
> 	 */
> 	private static final String FIELD_BOOT_CLASS_PATH = "bootClassPath";
> ```

Do we really want to send string values to a time series database?

---

*[inspectit.server/src/main/java/rocks/inspectit/server/processor/tsdb/impl/TimerDataToTsdbCmrProcessor.java, line 170 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/156#-KQericvWDnJU0vVBkVh:-KQericvWDnJU0vVBkVi:b9tls2z) ([raw file](https://github.com/inspectit/inspectit/blob/cef8d1b46e045a6db8d07185ff3d6e64b5882525/inspectit.server/src/main/java/rocks/inspectit/server/processor/tsdb/impl/TimerDataToTsdbCmrProcessor.java#L170)):*
> ```Java
> 		builder.tag(TAG_AGENT_NAME, agentName);
> 		builder.tag(TAG_METHOD_NAME, mIdent.getMethodName());
> 		builder.tag(TAG_CLASS_FQN, mIdent.getFQN());
> ```

just a small remark: getFQN returns package + class, not only class

---

*[inspectit.server/src/main/java/rocks/inspectit/server/tsdb/IInfluxDBService.java, line 12 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/156#-KQes1zBGZw9xQrxxCjr:-KQes1zBGZw9xQrxxCjs:b-rz72jg) ([raw file](https://github.com/inspectit/inspectit/blob/cef8d1b46e045a6db8d07185ff3d6e64b5882525/inspectit.server/src/main/java/rocks/inspectit/server/tsdb/IInfluxDBService.java#L12)):*
> ```Java
>  */
> public interface IInfluxDBService {
> 	/**
> ```

format - empty line missing

---

*[inspectit.server/src/main/java/rocks/inspectit/server/tsdb/impl/InfluxDBService.java, line 28 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/156#-KQeppogBmX1c2SLjZB2:-KQeppogBmX1c2SLjZB3:bfvp56f) ([raw file](https://github.com/inspectit/inspectit/blob/cef8d1b46e045a6db8d07185ff3d6e64b5882525/inspectit.server/src/main/java/rocks/inspectit/server/tsdb/impl/InfluxDBService.java#L28)):*
> ```Java
>  */
> @Component
> public class InfluxDBService implements InitializingBean, IInfluxDBService {
> ```

This is not a service (e.g. one that can be called from a client: agent / ui / rest etc.) but rather located in the Dao layer. Thus it should be moved there and renamed accordingly

---

*[inspectit.server/src/main/java/rocks/inspectit/server/tsdb/impl/InfluxDBService.java, line 223 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/156#-KQeuTLc-o8fORgiiJnc:-KQeuTLc-o8fORgiiJnd:bjdgxrn) ([raw file](https://github.com/inspectit/inspectit/blob/cef8d1b46e045a6db8d07185ff3d6e64b5882525/inspectit.server/src/main/java/rocks/inspectit/server/tsdb/impl/InfluxDBService.java#L223)):*
> ```Java
> 			influxDB.ping();
> 			return true;
> 		} catch (Exception e) {
> ```

Don't we have a concrete exception we could catch to know if it is really due to a connection error? Or we should at least log this to have the possiblity to fix this issue if needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit/inspectit/156#-:-KQew-Val7uZ9VQwtqjI:bza7s39)*

**Comment by stefansiegl** [comment]
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[inspectit.server/src/main/external-resources/config/default.xml, line 331 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/156#-KQeihfurK9vuVOuFAtl:-KQfK679oj0WT0d0osHP:buiy2fn) ([raw file](https://github.com/inspectit/inspectit/blob/cef8d1b46e045a6db8d07185ff3d6e64b5882525/inspectit.server/src/main/external-resources/config/default.xml#L331)):*
<details><summary><i>Previously, pbouillet (Patrice Bouillet) wrote…</i></summary>
> Something that is currently missing but which I would really like to have here (and for the database section, too) is a "Test" Button to identify if the configuration really works out.
</details>
I disagree that we need this right now for the very first iteration of it. It is a nice idea, but not relevant for the customer. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit/inspectit/156)*

**Comment by stefansiegl** [comment]
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[inspectit.server/src/main/java/rocks/inspectit/server/processor/tsdb/impl/BusinessTransactionToTsdbCmrProcessor.java, line 29 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/156#-KQenl_Davm3NpAk1x0k:-KQfKUmO6vfxMT0bRrkD:bopdf9i) ([raw file](https://github.com/inspectit/inspectit/blob/cef8d1b46e045a6db8d07185ff3d6e64b5882525/inspectit.server/src/main/java/rocks/inspectit/server/processor/tsdb/impl/BusinessTransactionToTsdbCmrProcessor.java#L29)):*
<details><summary><i>Previously, pbouillet (Patrice Bouillet) wrote…</i></summary>
> let's name the class with influx to make it concrete for now. In the future, I can think of having an intermediate layer in which you can define where the time series will be stored to. But for now, influx is the way to go and directly accessed.
</details>
I do not see us supporting multiple time series databases in any time soon. This is because the database is _part_ of inspectIT and part of the product. We do not support many databases. Sure we might switch at some time, but we only have a single database.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit/inspectit/156)*

**Comment by stefansiegl** [comment]
hm good point. I see that we need some testing at the least in order to stick at least a bit with our high quality integration approach. On the other hand, we do not know how the customer really wants to have the feature, so I propose to keep testing at a low priority right now. 

How about labelling this feature as experimental in the configuration? This actually would feel really good for me and would allow us to go without tests for iteration 1 (no doubts that we need tests for this in iteration2)

---

Review status: all files reviewed at latest revision, 18 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit/inspectit/156#-:-KQfM2SkZ6SDoilxgwcc:blerlb3)*

**Pull request merged**
