### PR TITLE
INSPECTIT-2105: squid:S1192 - String literals should not be duplicated

### PR DESCRIPTION
**Pull request by georgekankava**
This pull request is focused on resolving occurrences of Sonar rule
squid:S1192 - String literals should not be duplicated.
This pull request removes 140 minutes of technical debt.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1192
Please let me know if you have any questions.
George Kankava

---

This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit/94)

### CODE REVIEW

**Comment by ivansenic** [comment]
Hi George,

Thanks very much for your pull requests. I wanted to give you some pointers in order to merge these as quickly as possible:

- As you maybe noticed we run on our Jenkins the complete integration for each pull request as well. This helps us in noticing if there is something not fitting to our (strict) project rules. All the builds for your PRs failed as we have a rule that each commit message must be in format *INSPECTIT-XXX: Description of updates* (where XXX is number of ticket commit relates to). Thus, you need to adapt all the commit messages. I opened a ticket for you (https://inspectit-performance.atlassian.net/browse/INSPECTIT-2105), so you can relate to this one in all your PRs. We also invite you to open account on our Atlassian if you like.
- As soon as you update your PR the new builds will start on Jenkins. Note that these must be green in order to be able to merge the PR.
- You can also check if everything is OK with your updates by running ```./gradlew analyze``` in the root of the project. This would run all the tests and all the static analysis tools. If the build is green, you can be sure that it would also pass on Jenkins as well.
- We use reviewable.io for reviewing the files, you can always click on the Reviewable icon to see all the comments there. For you we will also make sure all comments are also visible in GitHub, so basically you don't need to use Reviewable if you don't like it.

Hope this helps. I will review all of your PRs in a moment, so if there is anything else you will receive a separate comment.

Thanks once again.

Greets,
Ivan

**Comment by ivansenic** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/analyzer/impl/ByteCodeAnalyzer.java, line 53 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/94#-KJFIFpCnP0a5h4BWJ9g:-KJFIFpDj5EXoy_5U655:-1139961391) ([raw file](https://github.com/inspectit/inspectit/blob/3265c2363657c71bd05ff28c985e2c5bdadd9678/inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/analyzer/impl/ByteCodeAnalyzer.java#L53)):*
> ```Java
> public class ByteCodeAnalyzer implements IByteCodeAnalyzer {
> 
> 	public static final String ERROR_OCCURRED_INSTRUMENTING_THE_BYTE_CODE_OF_CLASS = "Error occurred instrumenting the byte code of class ";
> ```

We have strict JavaDoc rules, where all fields/methods must be documented. Even in situations like this when it's clear what the field is. We still require a small javadoc like:

```
/**
 * Error message for problems during instrumentation.
 */
``` 

Also note that our formatting  defines empty lines between each fields/methods. All formatting rules you would have automatically installed if you follow our [Development Environment](https://inspectit-performance.atlassian.net/wiki/display/DEV/Development+Environment) setup information.

Please make sure to fix this in all classes in this PR, as the same problem occurs in all of them.

---

*[inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/connection/impl/KryoNetConnection.java, line 214 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/94#-KJFK_cUYshCqBwtEMmD:-KJFK_cUYshCqBwtEMmE:-1845956909) ([raw file](https://github.com/inspectit/inspectit/blob/3265c2363657c71bd05ff28c985e2c5bdadd9678/inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/connection/impl/KryoNetConnection.java#L214)):*
> ```Java
> 			log.error("Could not obtain network interfaces from this machine!");
> 			if (log.isTraceEnabled()) {
> 				log.trace(UNREGISTER_PLATFORM_LIST_STRING, socketException);
> ```

Here there is an obvious mistake in the code. This message should be registerPlatform(List, String) as we are in register method. This was not your mistake, it was already an existing one.

Thus the used literal should be changed. Also two lines below we have the same problem.

---

*[inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/hooking/impl/HookInstrumenter.java, line 35 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/94#-KJFJqD5G31PZPjybsDt:-KJFJqD6-jebQxjs9vQq:2135812491) ([raw file](https://github.com/inspectit/inspectit/blob/3265c2363657c71bd05ff28c985e2c5bdadd9678/inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/hooking/impl/HookInstrumenter.java#L35)):*
> ```Java
> public class HookInstrumenter implements IHookInstrumenter {
> 
> 	public static final String DISPATCH_FIRST_METHOD_AFTER_BODY = ".dispatchFirstMethodAfterBody(";
> ```

I am not sure if the string literals rule should be applied here. It's much more easier to read the code with the strings are directly placed in the code. Especially the combination that includes THROW_E and L_ARGS. I would advise we keep this class as it was. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit/inspectit/94)*

**Comment by georgekankava** [comment]
@ivansenic Hi Ivan. Thanks for the instructions. Changes applied.

**Comment by ivansenic** [comment]
Hi @georgekankava,

Unfortunately there are conflicts with our current master. Can you resolve please. I would look at it again then. Thanks.

**Comment by georgekankava** [comment]
@ivansenic Hi Ivan. PR Updated.

**Comment by ivansenic** [comment]
Reviewed 3 of 6 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit/inspectit/94)*

**Comment by ivansenic** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/connection/impl/KryoNetConnection.java, line 48 \[r3\]](https://reviewable.io:443/reviews/inspectit/inspectit/94#-KLVSVviBDzuqkYYGgNb:-KLVSVvjLZESoEgwwbND:1057873786) ([raw file](https://github.com/inspectit/inspectit/blob/af791e36518451bd9a827634983f47f00e6608ac/inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/connection/impl/KryoNetConnection.java#L48)):*
> ```Java
> public class KryoNetConnection implements IConnection {
> 	/**
> 	 * Register platform message
> ```

Checkstyle complains here:

```
First sentence should end with a period.
```

Could you add a dot (```.```) to the end of all these new javadoc. Thanks.

---

*[inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/connection/impl/KryoNetConnection.java, line 245 \[r3\]](https://reviewable.io:443/reviews/inspectit/inspectit/94#-KLVSLBcXVqq1E6Q8kQm:-KLVSLBcXVqq1E6Q8kQn:180372009) ([raw file](https://github.com/inspectit/inspectit/blob/af791e36518451bd9a827634983f47f00e6608ac/inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/connection/impl/KryoNetConnection.java#L245)):*
> ```Java
> 		} catch (ExecutionException executionException) {
> 			if (log.isTraceEnabled()) {
> 				log.trace("register(String, String)", executionException);
> ```

Could you replace "register(String, String)" with REGISTER_PLATFORM_LIST_STRING.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit/inspectit/94)*

**Comment by georgekankava** [comment]
@ivansenic Hi Ivan. PR updated.

**Comment by ivansenic** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit/inspectit/94)*

**Pull request closed without merging**
