### PR TITLE
INSPECTIT-2105: squid:S1854 - Dead stores should be removed

### PR DESCRIPTION
**Pull request by georgekankava**
This pull request is focused on resolving occurrences of Sonar rule
squid:S1854 - Dead stores should be removed.
This pull request removes 180 minutes of technical debt.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1854
Please let me know if you have any questions.
George Kankava

---
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit/95)

### CODE REVIEW

**Comment by ivansenic** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/sensor/platform/provider/ibm/IbmJava6OperatingSystemInfoProvider.java, line 90 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/95#-KJFN1kHnXRgjRv620L2:-KJFN1kHnXRgjRv620L3:1624539980) ([raw file](https://github.com/inspectit/inspectit/blob/c14c84b287378e462e0d1795c4f6ecfa805c0d8c/inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/sensor/platform/provider/ibm/IbmJava6OperatingSystemInfoProvider.java#L90)):*
> ```Java
> 	 */
> 	private void initAndCheckEnvironment() throws Exception {
> 		Class<?> ibmOperatingSystemMxBeanClass;
> ```

Could you combine this line and one blow into one line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit/inspectit/95)*

**Comment by georgekankava** [comment]
@ivansenic Updated.

**Comment by ivansenic** [comment]
Hi @georgekankava,

Unfortunately there are conflicts with our current master. Can you resolve please. I would look at it again then. Thanks.

**Comment by georgekankava** [comment]
@ivansenic Thanks for the comment. PR updated.

**Comment by ivansenic** [comment]
Reviewed 5 of 7 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/platform/CpuInformationTest.java, line 1 \[r3\]](https://reviewable.io:443/reviews/inspectit/inspectit/95#-KLVRS6XxXVCi79208pf:-KLVRS6XxXVCi79208pg:-617515089) ([raw file](https://github.com/inspectit/inspectit/blob/69f94c733c8d05b089758567aafd86bda8e84a08/inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/platform/CpuInformationTest.java#L1)):*
> ```Java
> 
> ```

Please remove this added empty line. Maybe your formatting settings are not the same as ours and this was automatically added :) Other than that it's all fine I would like to push this. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit/inspectit/95)*

**Comment by georgekankava** [comment]
@PR Updated.

**Comment by ivansenic** [comment]
Hi again,

Seams that your changes in the CpuInformationTest are breaking the test. Seams like your re-basing was wrong and you overwrote the change in the test in one of the previous commits. Please make sure that no unnecessary changes are applied to the test. The failed tests:

```
ise@ise-CELSIUS-H730:~/workspace/inspectIT/ivansenic-inspectit/inspectit.agent.java$ ../gradlew analyze
:cpdCheck
CPD found duplicate code. See the report at file:///home/ise/workspace/inspectIT/ivansenic-inspectit/build/QA/static_analysis/cpd/main.xml
:cpdHtmlReport
:inspectit.shared.all:compileJava UP-TO-DATE
:inspectit.shared.all:processResources UP-TO-DATE
:inspectit.shared.all:classes UP-TO-DATE
:inspectit.shared.all:jar
:inspectit.agent.java:compileJava
:inspectit.agent.java:processResources UP-TO-DATE
:inspectit.agent.java:classes
:inspectit.agent.java:checkstyleMain
:inspectit.agent.java:checkstyleHtmlReport
:inspectit.agent.java:findbugsMain
:inspectit.agent.java:findbugsHtmlReport
:inspectit.agent.java:pmdMain
:inspectit.agent.java:pmdHtmlReport
:inspectit.agent.java:instrument
Cobertura 2.1.1 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
:inspectit.agent.java:copyCoberturaDatafile
:inspectit.shared.all:compileTestJava UP-TO-DATE
:inspectit.shared.all:processTestResources UP-TO-DATE
:inspectit.shared.all:testClasses UP-TO-DATE
:inspectit.shared.all:jarTest UP-TO-DATE
:inspectit.agent.java:compileTestJava
/home/ise/workspace/inspectIT/ivansenic-inspectit/inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/platform/CpuInformationTest.java:79: error: cannot find symbol
                        when(idManager.getPlatformId()).thenReturn(platformIdent);
                             ^
  symbol:   variable idManager
  location: class CpuInformationTest.Update
/home/ise/workspace/inspectIT/ivansenic-inspectit/inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/platform/CpuInformationTest.java:80: error: cannot find symbol
                        when(idManager.getRegisteredSensorTypeId(sensorType)).thenReturn(sensorType);
                             ^
  symbol:   variable idManager
  location: class CpuInformationTest.Update
/home/ise/workspace/inspectIT/ivansenic-inspectit/inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/platform/CpuInformationTest.java:85: error: method update in class CpuInformation cannot be applied to given types;
                        cpuInfo.update(coreService, sensorType);
                               ^
  required: ICoreService
  found: ICoreService,long
  reason: actual and formal argument lists differ in length
/home/ise/workspace/inspectIT/ivansenic-inspectit/inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/platform/CpuInformationTest.java:134: error: cannot find symbol
                        when(idManager.getPlatformId()).thenReturn(platformIdent);
                             ^
  symbol:   variable idManager
  location: class CpuInformationTest.Update
/home/ise/workspace/inspectIT/ivansenic-inspectit/inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/platform/CpuInformationTest.java:135: error: cannot find symbol
                        when(idManager.getRegisteredSensorTypeId(sensorType)).thenReturn(sensorType);
                             ^
  symbol:   variable idManager
  location: class CpuInformationTest.Update
/home/ise/workspace/inspectIT/ivansenic-inspectit/inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/platform/CpuInformationTest.java:144: error: method update in class CpuInformation cannot be applied to given types;
                        cpuInfo.update(coreService, sensorType);
                               ^
  required: ICoreService
  found: ICoreService,long
  reason: actual and formal argument lists differ in length
/home/ise/workspace/inspectIT/ivansenic-inspectit/inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/platform/CpuInformationTest.java:169: error: method update in class CpuInformation cannot be applied to given types;
                        cpuInfo.update(coreService, sensorType);
                               ^
  required: ICoreService
  found: ICoreService,long
  reason: actual and formal argument lists differ in length
/home/ise/workspace/inspectIT/ivansenic-inspectit/inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/platform/CpuInformationTest.java:202: error: cannot find symbol
                        when(idManager.getPlatformId()).thenThrow(new IdNotAvailableException("expected"));
                             ^
  symbol:   variable idManager
  location: class CpuInformationTest.Update
/home/ise/workspace/inspectIT/ivansenic-inspectit/inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/platform/CpuInformationTest.java:203: error: cannot find symbol
                        when(idManager.getRegisteredSensorTypeId(sensorType)).thenThrow(new IdNotAvailableException("expected"));
                             ^
  symbol:   variable idManager
  location: class CpuInformationTest.Update
/home/ise/workspace/inspectIT/ivansenic-inspectit/inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/platform/CpuInformationTest.java:207: error: method update in class CpuInformation cannot be applied to given types;
                        cpuInfo.update(coreService, sensorType);
                               ^
  required: ICoreService
  found: ICoreService,long
  reason: actual and formal argument lists differ in length
10 errors
:inspectit.agent.java:compileTestJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':inspectit.agent.java:compileTestJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
``` 

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit/inspectit/95#-:-KLWXvvSDmrUObZUqo2h:-709354512)*

**Comment by georgekankava** [comment]
@ivansenic I have removed CpuInformationTest from the commit. Hope this will help.

**Comment by ivansenic** [comment]
OK that works thanks.

---

Reviewed 1 of 7 files at r3, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit/inspectit/95#-:-KLWcWKxF6EbhO9ZkEdA:873333261)*

**Pull request closed without merging**
