### PR TITLE
Fix links to License as well as docker pulls/downloads

### PR DESCRIPTION
**Pull request by jaikiran**
The commit here fixes some of the broken links in the Readme file of the project.

---
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit/261)

### CODE REVIEW

**Comment by pbouillet** [comment]
Thank you very much for providing a fix to our README. Before I can merge this, could you prepend a ticket number (https://inspectit-performance.atlassian.net/browse/INSPECTIT-2389) to the commit message? We enforce this rule to have a certain transparency for us:

> INSPECTIT-2389: Fix links to License as well as docker pulls/downloads

**Comment by jaikiran** [comment]
@pbouillet, I just updated the commit message. Thanks for creating that ticket.

**Comment by pbouillet** [comment]
Could you add a colon after the ticket? Otherwise Jenkins won't accept it :smile: . Thanks :+1:

**Comment by jaikiran** [comment]
@pbouillet, just looked up some of the commits in this repo and I've updated this PR and I think I got it right this time :)

**Comment by pbouillet** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit/inspectit/261)*

**Pull request merged**
