### PR TITLE
INSPECTIT-2092: Fixed broken links in README.md

### PR DESCRIPTION
**Pull request by mariusoe**
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit/82)

### CODE REVIEW

**Comment by ivansenic** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 1 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/82#-KGMSpfoKxoeplKrk7ff:-KGMSpfoKxoeplKrk7fg:364391568) ([raw file](https://github.com/inspectit/inspectit/blob/c8dccf4ac260083a67f17863d6bb3c35e382b078/README.md#L1)):*
here as well please ../master/license/LICENSE.txt

---

*[README.md, line 82 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/82#-KGMSM9lB_l7hh3FhkdJ:-KGMSM9lB_l7hh3FhkdK:1171235306) ([raw file](https://github.com/inspectit/inspectit/blob/c8dccf4ac260083a67f17863d6bb3c35e382b078/README.md#L82)):*
We don't have a manual packages on our website, only the installers, maybe we should point them to the https://github.com/inspectIT/inspectIT/releases (maybe this makes sense for both download links what do you think?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit/inspectit/82)*

**Comment by ivansenic** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit/inspectit/82)*

**Comment by ivansenic** [comment]
Can you check in addition all the links to our website if those have changed and are working. Thx

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit/inspectit/82#-:-KGMT8edW9qz7PKA4J42:-1942576810)*

**Comment by mariusoe** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 1 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/82#-KGMSpfoKxoeplKrk7ff:-KGMU7Qcgl1OjXhgveDf:-1408320074) ([raw file](https://github.com/inspectit/inspectit/blob/c8dccf4ac260083a67f17863d6bb3c35e382b078/README.md#L1)):*
Oh, didn't noticed this link..

---

*[README.md, line 82 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/82#-KGMSM9lB_l7hh3FhkdJ:-KGMWCnegHEQevlaaVhH:-1405421554) ([raw file](https://github.com/inspectit/inspectit/blob/c8dccf4ac260083a67f17863d6bb3c35e382b078/README.md#L82)):*
Yes, I think we should provide the github site, too. Especially if someone wants an older version..

Maybe we can write something like this:

You can get inspectIT in three ways:
- Download the latest stable release from our [website]
- Download a specific version from [GitHub]
- Use a pre-built [Docker image]

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit/inspectit/82)*

**Comment by ivansenic** [comment]
*[README.md, line 4 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/82#-KGMX1hZrnzwJontEZDS:-KGMX1hZrnzwJontEZDT:808886589) ([raw file](https://github.com/inspectit/inspectit/blob/c8dccf4ac260083a67f17863d6bb3c35e382b078/README.md#L4)):*
can you make here this link to the website clickable as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit/inspectit/82)*

**Comment by ivansenic** [comment]
*[README.md, line 82 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/82#-KGMSM9lB_l7hh3FhkdJ:-KGMXAQ6GlUOWXyXhBPE:913375706) ([raw file](https://github.com/inspectit/inspectit/blob/c8dccf4ac260083a67f17863d6bb3c35e382b078/README.md#L82)):*
Hmm not sure what to do.. Maybe keep the old structure and just use the link to the github releases.. Anyway our download links from the website go back to the github?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit/inspectit/82)*

**Comment by ivansenic** [comment]
*[README.md, line 4 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/82#-KGMX1hZrnzwJontEZDS:-KGMX_wE5JDBviiAYToO:1361045384) ([raw file](https://github.com/inspectit/inspectit/blob/c8dccf4ac260083a67f17863d6bb3c35e382b078/README.md#L4)):*
Forget it already is!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit/inspectit/82)*

**Comment by mariusoe** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 82 \[r1\]](https://reviewable.io:443/reviews/inspectit/inspectit/82#-KGMSM9lB_l7hh3FhkdJ:-KGMY3X0yWs9847ChbDZ:1835467404) ([raw file](https://github.com/inspectit/inspectit/blob/c8dccf4ac260083a67f17863d6bb3c35e382b078/README.md#L82)):*
Yes they are linking to files, located on Github, but I think it is good to link the download section of the website. Because users have a nice overview and are able to download the files directly (don't have to look which one is the latest stable version..)

or we don't link the download section of the website to get the latest version, but this: https://github.com/inspectIT/inspectIT/releases/latest

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit/inspectit/82)*

**Pull request closed without merging**
